package com.jhao.playdemo.applications.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.jhao.playdemo.applications.AppInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "APP_INFO".
*/
public class AppInfoDao extends AbstractDao<AppInfo, Void> {

    public static final String TABLENAME = "APP_INFO";

    /**
     * Properties of entity AppInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", false, "NAME");
        public final static Property PackageName = new Property(1, String.class, "packageName", false, "PACKAGE_NAME");
        public final static Property IsUser = new Property(2, boolean.class, "isUser", false, "IS_USER");
        public final static Property IsRom = new Property(3, boolean.class, "isRom", false, "IS_ROM");
        public final static Property AppVersion = new Property(4, String.class, "appVersion", false, "APP_VERSION");
    }


    public AppInfoDao(DaoConfig config) {
        super(config);
    }
    
    public AppInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"APP_INFO\" (" + //
                "\"NAME\" TEXT," + // 0: name
                "\"PACKAGE_NAME\" TEXT UNIQUE ," + // 1: packageName
                "\"IS_USER\" INTEGER NOT NULL ," + // 2: isUser
                "\"IS_ROM\" INTEGER NOT NULL ," + // 3: isRom
                "\"APP_VERSION\" TEXT);"); // 4: appVersion
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"APP_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AppInfo entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(2, packageName);
        }
        stmt.bindLong(3, entity.getIsUser() ? 1L: 0L);
        stmt.bindLong(4, entity.getIsRom() ? 1L: 0L);
 
        String appVersion = entity.getAppVersion();
        if (appVersion != null) {
            stmt.bindString(5, appVersion);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AppInfo entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(2, packageName);
        }
        stmt.bindLong(3, entity.getIsUser() ? 1L: 0L);
        stmt.bindLong(4, entity.getIsRom() ? 1L: 0L);
 
        String appVersion = entity.getAppVersion();
        if (appVersion != null) {
            stmt.bindString(5, appVersion);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public AppInfo readEntity(Cursor cursor, int offset) {
        AppInfo entity = new AppInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // name
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // packageName
            cursor.getShort(offset + 2) != 0, // isUser
            cursor.getShort(offset + 3) != 0, // isRom
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // appVersion
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AppInfo entity, int offset) {
        entity.setName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setPackageName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIsUser(cursor.getShort(offset + 2) != 0);
        entity.setIsRom(cursor.getShort(offset + 3) != 0);
        entity.setAppVersion(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(AppInfo entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(AppInfo entity) {
        return null;
    }

    @Override
    public boolean hasKey(AppInfo entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
